name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::520196876033:role/udemy.shima.github-actions.iam.role.frontend-deployment
          aws-region: ap-northeast-1
      - run: aws s3 sync . s3://udemy.shima.github-actions.s3.backet --exact-timestamps --region ap-northeast-1 --debug